package parsley;

import com.webobjects.appserver.WOContext;
import com.webobjects.appserver.WOElement;
import com.webobjects.appserver.WORequest;
import com.webobjects.appserver.WOResponse;
import com.webobjects.appserver.WOActionResults;

/**
 * Wraps the root element of every template Parsley parses, marking — at render time —
 * that the current response was generated by Parsley's template engine.
 *
 * <p>This is how {@link ParsleyRequestObserver} knows whether it may post-process a
 * response. The observer fires for <em>every</em> dispatched request (component pages,
 * served resources, direct actions, API responses, …), but it must only inject its dev
 * overlays into responses produced by rendering a component template — otherwise it
 * corrupts, say, a served {@code .js} file that happens to contain a {@code </body>}
 * substring. Because a plain-HTML template has no dynamic elements (and thus no
 * {@link ParsleyProxyElement}), the only reliable signal is set here, at the template
 * root, which renders for <em>every</em> Parsley template regardless of its content.
 *
 * <p>Delegation is otherwise transparent — all three request phases pass straight
 * through to the wrapped root; only {@code appendToResponse} additionally sets the flag.
 */
public class ParsleyTemplateRootElement extends WOElement {

	private final WOElement _root;

	ParsleyTemplateRootElement( final WOElement root ) {
		_root = root;
	}

	@Override
	public void appendToResponse( final WOResponse response, final WOContext context ) {
		ParsleyRequestObserver.markTemplateRendered();
		_root.appendToResponse( response, context );
	}

	@Override
	public void takeValuesFromRequest( final WORequest request, final WOContext context ) {
		_root.takeValuesFromRequest( request, context );
	}

	@Override
	public WOActionResults invokeAction( final WORequest request, final WOContext context ) {
		return _root.invokeAction( request, context );
	}
}
