package parsley;

import java.util.ArrayList;
import java.util.List;

import com.webobjects.appserver.WOResponse;
import com.webobjects.foundation.NSNotification;

public class ParsleyRequestObserver {

	/**
	 * FIXME: We probably shouldn't be using a ThreadLocal, seing as how WorkerThreads are reused in WO. It will work fine though, since the variable gets reset at the end of the request // Hugi 2025-03-26
	 */
	public static ThreadLocal<List<String>> errors = ThreadLocal.withInitial( ArrayList::new );

	/**
	 * Set when a Parsley-parsed template renders during the current request (by
	 * {@link ParsleyTemplateRootElement}). The observer only post-processes a response
	 * when this is set — i.e. only responses generated by Parsley's template engine, not
	 * served resources, direct actions, or API responses that merely happen to contain a
	 * {@code </body>} substring.
	 */
	private static final ThreadLocal<Boolean> templateRendered = ThreadLocal.withInitial( () -> Boolean.FALSE );

	/**
	 * Marks that a Parsley template rendered during the current request. Called from
	 * {@link ParsleyTemplateRootElement#appendToResponse}.
	 */
	static void markTemplateRendered() {
		templateRendered.set( Boolean.TRUE );
	}

	public void didHandleRequest( NSNotification notification ) {
		// Only touch responses produced by rendering a Parsley template — never served
		// resources, direct actions, etc. Reset the per-request flag now (worker threads
		// are reused) so the next request on this thread starts clean.
		final boolean wasTemplate = templateRendered.get();
		templateRendered.set( Boolean.FALSE );

		if( !wasTemplate ) {
			errors.set( new ArrayList<>() );
			return;
		}

		final WOResponse response = (WOResponse)notification.object();

		final StringBuilder injection = new StringBuilder();

		if( !errors.get().isEmpty() ) {
			final int errorCount = errors.get().size();

			injection.append( """
					<div style="width: 100%%; height: 100px; position: fixed; top: 0px; right: 0px; background-color: rgba(255,0,0,0.6); border-bottom: 2px solid red; color: white; padding: 32px; text-align: center; text-shadow: 1px 1px 2px black; pointer-events: none; z-index: 2147483647">
						<h2 style="font-size: 24px">%s %s %s on page</h2>
					</div>
					<div style="width: 100%%; height: 100%%; position: fixed; top: 100px; right: 0px; background-color: rgba(255,140,0,0.1); pointer-events: none; z-index: 2147483646; border: 0px solid red">
						&nbsp;
					</div>
					""".formatted( ParsleyConstants.HERB, errorCount, (errorCount == 1 ? "error" : "errors") ) );

			errors.set( new ArrayList<>() );
		}

		// The development controls strip, when enabled.
		if( Parsley.showControls() ) {
			injection.append( ParsleyControlsStrip.render( Parsley.showInlineErrorMessages() ) );
		}

		if( injection.length() > 0 ) {
			final String content = response.contentString();
			if( content != null && content.contains( "</body>" ) ) {
				response.setContent( content.replace( "</body>", injection + "</body>" ) );
			}
		}
	}
}