package parsley;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import com.webobjects.appserver.WOContext;
import com.webobjects.appserver.WOElement;
import com.webobjects.appserver.WOResponse;
import com.webobjects.foundation.NSNotification;

/**
 * Tests that {@link ParsleyRequestObserver} only post-processes responses generated by
 * Parsley's template engine — the fix for corrupting non-template responses (e.g. a
 * served {@code .js} file containing a {@code </body>} substring).
 */
class TestParsleyRequestObserver {

	@BeforeEach
	void reset() {
		ParsleyTestSupport.resetParsleyConfiguration();
		ParsleyRequestObserver.errors.set( new java.util.ArrayList<>() );
	}

	/** A response carrying the given body, as if it were a served resource / page. */
	private static NSNotification responseNotification( final String body ) {
		final WOResponse response = new WOResponse();
		response.setContent( body );
		return new NSNotification( "x", response );
	}

	/** Drives the observer with a pending error (the error overlay injects into </body>). */
	private static String runWithPendingError( final NSNotification n, final boolean templateRendered ) {
		ParsleyRequestObserver.errors.get().add( "boom" );
		if( templateRendered ) {
			ParsleyRequestObserver.markTemplateRendered();
		}
		new ParsleyRequestObserver().didHandleRequest( n );
		return ((WOResponse)n.object()).contentString();
	}

	@Test
	void leavesNonTemplateResponsesUntouched() {
		// No Parsley template rendered this "request" — the body must come out
		// byte-identical, even though it contains </body> and an error is pending.
		final String js = "function f(){ return '</body>'; } // idiomorph-style";
		final NSNotification n = responseNotification( js );

		final String out = runWithPendingError( n, false );

		assertTrue( out.equals( js ), "a non-template response must be byte-identical" );
	}

	@Test
	void injectsIntoTemplateResponses() {
		final NSNotification n = responseNotification( "<html><body>hi</body></html>" );

		final String out = runWithPendingError( n, true );

		assertTrue( out.contains( "error" ) && out.contains( "</body>" ),
				"a template response gets the error overlay injected before </body>: " + out );
		assertTrue( out.length() > "<html><body>hi</body></html>".length(), "content grew" );
	}

	@Test
	void markerElementSetsTheFlagAndDelegates() {
		final boolean[] rendered = { false };
		final WOElement inner = new WOElement() {
			@Override
			public void appendToResponse( final WOResponse response, final WOContext context ) {
				rendered[0] = true;
			}
		};

		new ParsleyTemplateRootElement( inner ).appendToResponse( new WOResponse(), null );
		assertTrue( rendered[0], "marker delegates to the wrapped root" );

		// The flag it set causes the next observer run to treat the response as a template.
		final NSNotification n = responseNotification( "<body></body>" );
		final String out = runWithPendingError( n, false ); // false: rely on the marker's flag, set above
		assertTrue( out.contains( "error" ), "the marker's flag enabled injection: " + out );
	}

	@Test
	void perRequestFlagDoesNotLeakToTheNextRequest() {
		// One template request, then a resource request on the same (reused) thread.
		runWithPendingError( responseNotification( "<body></body>" ), true );

		final String js = "var x = '</body>';";
		final String out = runWithPendingError( responseNotification( js ), false );
		assertFalse( out.contains( "error" ), "the flag from the prior request didn't leak" );
		assertTrue( out.equals( js ) );
	}
}
