name: Manually Publish package to GitHub Packages
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: s4u/maven-settings-action@v3.1.0
        with:
          repositories: '[{"id":"wocommunity.releases","name":"WOCommunity Releases Repository","url":"https://maven.wocommunity.org/content/groups/public","snapshots":{"enabled":false}}]'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

